### ISSUE TITLE
Unsanitized options results in 400-ish errors and mostly inaccessible admin settings

### ISSUE THREAD

**Issue by Varstahl** [covertnine/c9-admin#1]
Long story short, when you first install the addon no options are set, therefore `get_option($this->plugin_name)` returns `false`. Subsequently all instances of `get_option($this->plugin_name)[<pararameterName>]` result in a `bool[dictionaryKey]`, with a ton of errors.

I've managed to move the browser on my main monitor, where on a 2560x1440 screen I was able to access the C9-admin settings, enable and then disable any setting, thus fixing the issue.

I didn't provide a fix as there's multiple ways to approach this, you can just create the settings during plugin activation or create a private function inside `class-c9-admin.php` to wrap the option call and fallback to a default dictionary.

**Comment by dskrepps** [comment]
Was checking this out today and was immediately hit by a screen fulls of errors. After managing to get to settings they went away, so probably the same bug.

![Screenshot_2020-11-20_19-29-27](https://user-images.githubusercontent.com/868050/99862385-88b32600-2b67-11eb-8fa3-cdabe1facdea.png)

**Comment by Varstahl** [comment]
Looks like it, yes.

**Comment by covertnine** [comment]
I pushed an update today that I believe addresses this, but I’m having a hard time getting it to error out  

I have an issue with the admin bar setting still that I’m going to work out this weekend. 

Take a look

https://github.com/covertnine/c9-admin/commit/f9a5f034ad832328c3f2c71e7d270265c125fd1a

**Comment by Varstahl** [comment]
From my recollection of things, this issue appears only on new installations and that commit doesn't fix it. The default return value for [get_option()](https://developer.wordpress.org/reference/functions/get_option/) is `false`, so the line would still be evaluated as `isset(<bool>['suppress_update_notice'])`. I would honestly mirror get_option functionality in a class function like so:

```php
function c9_get_option($name) {
    $opt = get_option($this->plugin_name);
    return (((false !== $opt) && array_key_exists($name, $opt)) ? $opt[$name] : false);
}
```

At that point you could disregard most of the conditionals within your code, and instances like https://github.com/covertnine/c9-admin/blob/f9a5f034ad832328c3f2c71e7d270265c125fd1a/admin/class-c9-admin.php#L57 would just become

```php
if (c9_get_option('suppress_update_notice'))
```

Also, since mirroring the get_option behaviour, this works even if the return value is not simply `true` but a complex dataset.

**Note**: I wrote the code off the top of my head, and while it should work some test might be in order :D

**Comment by covertnine** [comment]
I’ll be honest this is definitely beyond my skillset. I’ll have to do some testing with it tomorrow, but I’ll see what I can do. 

-T

**Comment by dskrepps** [comment]
Both these solutions fix the errors except for the first, [line 41](https://github.com/covertnine/c9-admin/blob/dcccc0fe4bff3711fe4a9f5f046d817c90e2e2e9/admin/class-c9-admin.php#L41).

If you could change that line in your pull request to the following all errors are gone on my end.

```php
        if (!$this->c9_option('custom_skin')) {
```

But now I notice the settings page has more of the same errors in c9-admin-display.php.

**Comment by Varstahl** [comment]
oops, that line eluded me, thanks for reporting.

**Comment by covertnine** [comment]
Merged these and tested this morning. New version pushed to Wordpress.org. 

-T
